config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about", as: "about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search"
  get 'tagsearches/search', to: 'tagsearches#search'


  resources :groups, except: [:destroy] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
   end

  resources :users, only: [:index,:show,:edit,:update] do
            member do
            get :follows, :followers
            end
            resource :relationships, only: [:create, :destroy]
  end

  resources :users, only: [:show,:edit,:update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :book_comments, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
  validates :category, presence: true


  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

 #検索機能
 def self.looks(search, word)
    if search == "perfect_match"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "backword_math"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "partial_match"
       @book = Book.where("title LIKE?","#{word}")
    else
       @book = Book.all
    end
 end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
      belongs_to :user
      belongs_to :book

      validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true

  def includesUser?(user)
  group_users.exists?(user_id: user.id)
  end

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def is_owned_by?(user)
    owner.id == user.id
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

      belongs_to :follower, class_name: "User"
      belongs_to :followed, class_name: "User"


end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :read_counts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


#フォロー機能
 def follow(user_id)
   followers.create(followed_id: user_id)
 end


 def unfollow(user_id)
   followers.find_by(followed_id: user_id).destroy
 end


 def following?(user)
   following_users.include?(user)
 end

#検索機能
 def self.looks(search, word)
    if search == "perfect_match"
       @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
       @user = User.where("name LIKE?","#{word}")
    elsif search == "backword_match"
       @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
       @user = User.where("name LIKE?","#{word}")
    else
       @user = User.all
    end

 end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
       before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @books = @user.books
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @book = Book.new
    @following_users = @user.following_users
    @follower_users = @user.follower_users
  end

  def index
    @users = User.all
    @book = Book.new

  end

  def edit
     @user = User.find(params[:id])
     unless @user.id == current_user.id
     redirect_to user_path(current_user.id)
     else
     @user = User.find(params[:id])
     end
  end

   def update
    @user = User.find(params[:id])
    unless @user.id == current_user.id
    redirect_to user_path(@user)
    end

    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user)
    else
    render :edit
    end
   end

   def follows
      user = User.find(params[:id])
      @users = user.following_users
   end

   def followers
      user = User.find(params[:id])
      @user = user.follower_users
   end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td>フォロー<%= user.followers.count %></td>
        <td>フォロワー<%= user.followeds.count %></td>

        <% if current_user != user %>
        <% if current_user.following?(user) %>
        <td><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %></td>
        <% else %>
        <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "byn btn-success" %></td>
        <% end %>
        <% end %>
      </tr>
        <% end %>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
   <th>Follows</th>
    <td>
    <%= link_to follows_user_path(user) do %>
    <%= user.followers.count %>
    <% end %>
    </td>
  </tr>
  <tr>
   <th>Followers</th>
    <td>
    <%= link_to followers_user_path(user) do %>
    <%= user.followeds.count %>
    <% end %>
    </td>
  </tr>
  <tr>
    <td>
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "byn btn-success" %>
      <% end %>
    <% end %>
    </td>
  </tr>

</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= render 'layouts/errors', obj: @user %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Followers</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image, size: '50x50' %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <p>フォロー<%= user.followers.count %></p>
          <% end %>
        </td>
        <td>
          <%= link_to followers_user_path(user) do %>
            <p>フォロワー<%= user.followeds.count %></p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h2>Follows</h2>
  <table class='table'>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image, size: '50x50' %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= link_to follows_user_path(user) do %>
              <h6>フォロー<%= user.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(user) do %>
              <h6>フォロワー<%= user.followeds.count %></h6>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
<div class='row'>
<div class='col-md-3'>
<h2>User info</h2>
<%= render 'info', user: current_user %>
<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>
</div>
<div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %>
<%= render 'index',users: @users %>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>

    <div>
      <% unless @user.id == current_user.id %>
      <% if (current_user.following? @user) && (@user.following? current_user)  %>
      <% if @isRoom == true %>
      <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
      <% else %>
      <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
      <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

  <h3>投稿数の前日比・前週比</h3>
  <div class="table_width">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今日の投稿</th>
        <th>昨日の投稿</th>
        <th>前日比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
	  <td><%= @today_book.count %></td>
	  <td><%= @yesterday_book.count %></td>
        <% if @yesterday_book.count == 0 %>
	  <td>前日の投稿はなし</td>
        <% else %>
	  <td><% @the_day_before =   @today_book.count / @yesterday_book.count  %>
	  <%= (@the_day_before * 100).round %>%</td>
        <% end %>
        </tr>
      </tbody>
    </table>

    <table class="table table-bordered">
      <thead>
      <tr>
        <th>今週の投稿</th>
        <th>先週の投稿</th>
        <th>先週比</th>
      </tr>
      </thead>
      <tbody>
        <tr>
	  <td><%= @this_week_book.count %></td>
	  <td><%= @last_week_book.count %></td>
        <% if @last_week_book.count == 0 %>
	  <td>先週の投稿はなし</td>
        <% else %>
	  <td><% @the_week_before = @this_week_book.count / @last_week_book.count  %>
	  <%= (@the_week_before * 100).round %>%</td>
        <% end %>
        </tr>
      </tbody>
    </table>
</div>
</div>
<canvas id="myLineChart"></canvas>
  <script src="https://cdn.jsdelivr.net/npm/chart.js">
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6day_ago.count %>,
                <%= @books.created_5day_ago.count %>,
                <%= @books.created_4day_ago.count %>,
                <%= @books.created_3day_ago.count %>,
                <%= @books.created_2day_ago.count %>,
                <%= @books.created_yesterday.count %>,
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>