config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about", as: "about"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
  end
  get "search" => "searches#search"
  get 'tagsearches/search', to: 'tagsearches#search'


  resources :groups, except: [:destroy] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
   end

  resources :users, only: [:index,:show,:edit,:update] do
            member do
            get :follows, :followers
            end
            resource :relationships, only: [:create, :destroy]
  end

  resources :users, only: [:show,:edit,:update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :book_comments, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
  validates :category, presence: true


  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

 #検索機能
 def self.looks(search, word)
    if search == "perfect_match"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "backword_math"
       @book = Book.where("title LIKE?","#{word}")
    elsif search == "partial_match"
       @book = Book.where("title LIKE?","#{word}")
    else
       @book = Book.all
    end
 end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
      belongs_to :user
      belongs_to :book

      validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true

  def includesUser?(user)
  group_users.exists?(user_id: user.id)
  end

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def is_owned_by?(user)
    owner.id == user.id
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

      belongs_to :follower, class_name: "User"
      belongs_to :followed, class_name: "User"


end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :read_counts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }


#フォロー機能
 def follow(user_id)
   followers.create(followed_id: user_id)
 end


 def unfollow(user_id)
   followers.find_by(followed_id: user_id).destroy
 end


 def following?(user)
   following_users.include?(user)
 end

#検索機能
 def self.looks(search, word)
    if search == "perfect_match"
       @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
       @user = User.where("name LIKE?","#{word}")
    elsif search == "backword_match"
       @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
       @user = User.where("name LIKE?","#{word}")
    else
       @user = User.all
    end

 end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
      before_action :authenticate_user!

  def show
    @books = Book.find(params[:id])
    unless ReadCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, book_id: @books.id)
      current_user.read_counts.create(book_id: @books.id)
    end

    @user = @books.user
    @book = Book.new
    @book_comment = BookComment.new
    

  end


  def index

    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.all.sort {|a,b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
    @book = Book.new
    @user = current_user

    if params[:latest]
    @books = Book.latest
    elsif params[:old]
    @books = Book.old
    elsif params[:star_count]
    @books = Book.star_count
    else
    @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
     @book = Book.find(params[:id])
     unless @book.user.id == current_user.id
     redirect_to books_path
     end
  end

  def update
     @book = Book.find(params[:id])
     unless @book.user.id == current_user.id
     redirect_to books_path
     end
     if @book.update(book_params)
     flash[:notice] = "Book was successfully updated."
     redirect_to book_path(@book.id)
     else
     @books = Book.all
     render :edit
     end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorite.html.erb
<% if @books.favorited_by?(current_user) %>
<%= link_to book_favorites_path(@books), method: :delete remote: true, data: {"turbolinks" => false} do %>♥<%= @books.favorites.count %>

<% end %>

<% else %>

<%= link_to book_favorites_path(@books), method: :post remote: true, data: {"turbolinks" => false} do %>♡<%= @books.favorites.count %>

<% end %>

<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <% if book.id.nil? %>
    <div class="form-group" id="star">
      <%= f.label :star %>
      <%= f.hidden_field :star, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[star]',
        };
        raty(elem, opt);
      });
    </script>
  <% else %>
    <div class="form-group">
      <%= render "static_rate", book: book %>
    </div>
  <% end %>

  <div class="form-group">
  <label>Category</label>
  <%= f.text_field :category,class: 'form-control book_category' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>

　　    <td><% if book.category.present? %><%=link_to book.category,tagsearches_search_path(content: book.category) %>
　　    <% end %></td>
        <td id="favorite<%= book.id %>" >
        <%= render 'favorites/favorite', book: book %>
        </td>
        <td>コメント件数:<span id="comment_count"><%= book.book_comments.count %></span></td>
        <td><%= render "books/static_rate", book: book %></td>
    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= book.id %>');
  if (elem == null) return;

  elem.innerHTML = "";
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= book.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
       <%= link_to '新しい順', books_path(latest: "true") %>
      |<%= link_to '古い順', books_path(old: "true") %>
      |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		<tbody>
  		  <tr>
          <td><%= link_to(@books.user) do %>
            <%= image_tag @books.user.get_profile_image, size:"50x50" %><br>
            <%= @books.user.name %>
            <% end %>
          </td>
          <td><%= link_to @books.title, @book %></td>
          <td><%= @books.body %></td>
          <td>閲覧数: <%= @books.read_counts.count %></td>
          <td>
　　      <% if @books.category.present? %>
　　　　  <%=link_to @books.category,tagsearches_search_path(content:@book.category)%>
　　      <% end %>
          </td>

          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@books), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @books, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% end %>
            <td id="favorite<%= @books.id %>">
            <%= render 'favorites/favorite', book: @books %>
            </td>
            <td>コメント件数:<span id="comment_counter"><%= @books.book_comments.count %></span></td>
            <td><%= render "static_rate", book: @books %></td>
        </tr>




         <td id="book_comments">
         <%= render 'book_comments/show', books: @books, book_comment: @book_comment %>
         </td>

        </tbody>
        </div>
        </table>


      <td id="comment-form">
      <%= render 'book_comments/form', books: @books, book_comment: @book_comment %>
      </td>
      </div>

  </div>
</div>